# Generated by Django 6.0.5 on 2026-05-15 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Lengkap')),
                ('nik', models.CharField(max_length=20, unique=True, verbose_name='NIK')),
                ('alamat', models.TextField(blank=True, verbose_name='Alamat')),
                ('telepon', models.CharField(blank=True, max_length=20, verbose_name='No. Telepon')),
                ('tanggal_bergabung', models.DateField(auto_now_add=True, verbose_name='Tanggal Bergabung')),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Non-Aktif')], default='aktif', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Anggota',
                'verbose_name_plural': 'Anggota',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='HargaGabah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal Berlaku')),
                ('harga_per_100kg', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga per 100 kg (Rp)')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan Khusus')),
            ],
            options={
                'verbose_name': 'Harga Gabah',
                'verbose_name_plural': 'Harga Gabah',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='Pengeluaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('kategori', models.CharField(choices=[('operasional', 'Operasional'), ('gaji', 'Gaji'), ('transport', 'Transport'), ('peralatan', 'Peralatan'), ('lainnya', 'Lainnya')], default='operasional', max_length=50, verbose_name='Kategori')),
                ('keterangan', models.CharField(max_length=300, verbose_name='Keterangan')),
                ('jumlah_rp', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Jumlah (Rp)')),
            ],
            options={
                'verbose_name': 'Pengeluaran',
                'verbose_name_plural': 'Pengeluaran',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='PenjualanGabah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal Penjualan')),
                ('jumlah_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jumlah (kg)')),
                ('harga_per_100kg', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga per 100 kg (Rp)')),
                ('total_rp', models.DecimalField(decimal_places=2, help_text='Otomatis dihitung: (jumlah_kg / 100) × harga_per_100kg', max_digits=15, verbose_name='Total (Rp)')),
                ('pembeli', models.CharField(max_length=200, verbose_name='Nama Pembeli')),
                ('keterangan', models.TextField(blank=True, verbose_name='Keterangan')),
            ],
            options={
                'verbose_name': 'Penjualan Gabah',
                'verbose_name_plural': 'Penjualan Gabah',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='IuranPanen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(help_text='Contoh: Januari 2024', max_length=50, verbose_name='Periode')),
                ('jumlah_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jumlah (kg)')),
                ('tanggal', models.DateField(verbose_name='Tanggal Iuran')),
                ('harga_per_100kg', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga per 100 kg (Rp)')),
                ('nilai_rp', models.DecimalField(decimal_places=2, help_text='Otomatis dihitung: (jumlah_kg / 100) × harga_per_100kg', max_digits=15, verbose_name='Nilai (Rp)')),
                ('keterangan', models.TextField(blank=True, verbose_name='Keterangan')),
                ('anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gabah.anggota', verbose_name='Anggota')),
            ],
            options={
                'verbose_name': 'Iuran Panen Gabah',
                'verbose_name_plural': 'Iuran Panen Gabah',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='SimpanPinjam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('simpanan', 'Simpanan'), ('pinjaman', 'Pinjaman')], max_length=10, verbose_name='Tipe')),
                ('jumlah_rp', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Jumlah (Rp)')),
                ('bunga_persen', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Bunga (%)')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('jatuh_tempo', models.DateField(blank=True, null=True, verbose_name='Jatuh Tempo')),
                ('keterangan', models.TextField(blank=True, verbose_name='Keterangan')),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('lunas', 'Lunas')], default='aktif', max_length=10, verbose_name='Status')),
                ('anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gabah.anggota', verbose_name='Anggota')),
            ],
            options={
                'verbose_name': 'Simpan Pinjam',
                'verbose_name_plural': 'Simpan Pinjam',
                'ordering': ['-tanggal'],
            },
        ),
    ]
