# Generated by Django 6.0.5 on 2026-05-16 03:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gabah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iuranpanen',
            name='keterangan',
            field=models.TextField(blank=True, default='', verbose_name='Keterangan'),
        ),
        migrations.AlterField(
            model_name='iuranpanen',
            name='nilai_rp',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Otomatis dihitung: (jumlah_kg / 100) x harga_per_100kg', max_digits=15, verbose_name='Nilai (Rp)'),
        ),
        migrations.AlterField(
            model_name='iuranpanen',
            name='periode',
            field=models.CharField(max_length=50, verbose_name='Periode'),
        ),
    ]
