# Generated by Django 6.0.5 on 2026-05-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gabah', '0002_alter_iuranpanen_keterangan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BukuKas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal Transaksi')),
                ('tipe', models.CharField(choices=[('masuk', 'Kas Masuk'), ('keluar', 'Kas Keluar')], max_length=10, verbose_name='Tipe Arus Kas')),
                ('kategori', models.CharField(choices=[('iuran_panen', 'Iuran Panen Gabah'), ('penjualan_gabah', 'Penjualan Gabah'), ('simpanan_masuk', 'Simpanan Anggota Masuk'), ('pinjaman_keluar', 'Pinjaman Anggota Keluar'), ('pinjaman_masuk', 'Pengembalian Pinjaman Anggota'), ('operasional', 'Biaya Operasional'), ('lainnya', 'Lainnya')], max_length=20, verbose_name='Kategori')),
                ('jumlah_rp', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Jumlah (Rp)')),
                ('keterangan', models.TextField(blank=True, verbose_name='Keterangan')),
                ('referensi', models.CharField(blank=True, help_text='Opsional: No Kwitansi atau ID Transaksi Asal', max_length=100, verbose_name='No. Referensi')),
            ],
            options={
                'verbose_name': 'Buku Kas',
                'verbose_name_plural': 'Buku Kas',
                'ordering': ['-tanggal'],
            },
        ),
    ]
